### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by viniboi0** [ififfy/flipflip#324]
[[Please describe the bug and how to reproduce it]]

FlipFlip Version: 3.2.2
```
TypeError: Cannot read property 'url' of undefined
at NG (file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1410:212916)
    at file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1330:18513
    at div
    at file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:11:82945
    at file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1249:72241
    at Hv (file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1322:305130)
    at Rn (file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1322:14032)
    at Dn (file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1322:13749)
    at Nn (file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1322:14168)
    at f (file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1410:735234)
    at hZ (file:///C:/Users/v_cou/OneDrive/Documents/FlipFlip-win32-x64/resources/app/dist/renderer.bundle.js:1410:713285)
```

**Comment by StarrHelixx** [comment]
There is no way for me to fix this without instructions on how to reproduce the error
